name: math_evaluator
description: A library for parsing and evaluating simple math expressions.
version: 0.3.2
homepage: https://github.com/balthild/math_evaluator
author: balthild <ibalthild@gmail.com>

environment:
  sdk: '>=2.0.0-dev.46.0 <2.0.0'

dev_dependencies:
  test: ^0.12.30
